import { Arimo } from "next/font/google";
import NavbarComponent from "@/app/components/Navbar";
import FooterComponent from "@/app/components/Footer";
import "./globals.css";

const arimo = Arimo({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Skill Sphere",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className="h-full antialiased light" 
      style={{ colorScheme: "light" }}     
      suppressHydrationWarning
    >
      <body className={`${arimo.className} min-h-full flex flex-col bg-white text-slate-900`}>
        <NavbarComponent />
        <main className="flex-grow">
          {children}
        </main>
        <FooterComponent />
      </body>
    </html>
  );
}